# NumPy Functions:

In [1]:
import numpy as np

# arange()

In [4]:
# np.arange(start, Ende, steps)
ar_1d = np.arange(1,13)
print(ar_1d)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [5]:
even_ar = np.arange(1,13,2)
print(even_ar)

[ 1  3  5  7  9 11]


# linspace()

In [6]:
np.linspace(1,5,4)

array([1.        , 2.33333333, 3.66666667, 5.        ])

# reshape()

In [10]:
ar_2d = ar_1d.reshape(3,4)
print(ar_2d)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [11]:
ar_23d = ar_1d.reshape(2, 3, 2)
print(ar_23d)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [14]:
ar = np.arange(1,13).reshape(2,6)
print(ar)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


# ravel() or flatten()

In [15]:
ar.ravel()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [16]:
ar.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

# transpose()

In [17]:
ar.transpose()

array([[ 1,  7],
       [ 2,  8],
       [ 3,  9],
       [ 4, 10],
       [ 5, 11],
       [ 6, 12]])

In [18]:
ar.T

array([[ 1,  7],
       [ 2,  8],
       [ 3,  9],
       [ 4, 10],
       [ 5, 11],
       [ 6, 12]])