# Random sampling with numpy

In [1]:
import numpy as np
import random

In [2]:
np.random.random(1)

array([0.95838366])

In [3]:
np.random.random((3,3))

array([[0.64555877, 0.09633428, 0.01265041],
       [0.91263205, 0.09600067, 0.64901654],
       [0.69043289, 0.38471812, 0.71209971]])

In [5]:
np.random.randint(1,4)

1

In [6]:
np.random.randint(1,4, (4,4))

array([[2, 1, 2, 3],
       [1, 1, 2, 2],
       [3, 3, 3, 3],
       [1, 2, 3, 2]])

In [7]:
np.random.randint(1,4, (2,4,4))

array([[[3, 1, 3, 3],
        [3, 1, 3, 3],
        [2, 3, 1, 3],
        [2, 2, 1, 3]],

       [[3, 3, 2, 3],
        [2, 2, 2, 1],
        [2, 2, 2, 2],
        [2, 1, 3, 2]]])

In [9]:
np.random.seed(10)
np.random.randint(1,4, (2,4,4))

array([[[2, 2, 1, 1],
        [2, 1, 2, 2],
        [1, 2, 2, 3],
        [1, 2, 1, 3]],

       [[1, 3, 1, 1],
        [1, 3, 1, 3],
        [3, 2, 1, 1],
        [3, 2, 3, 2]]])

In [10]:
np.random.seed(10)
np.random.randint(1,4, (2,4,4))

array([[[2, 2, 1, 1],
        [2, 1, 2, 2],
        [1, 2, 2, 3],
        [1, 2, 1, 3]],

       [[1, 3, 1, 1],
        [1, 3, 1, 3],
        [3, 2, 1, 1],
        [3, 2, 3, 2]]])

In [11]:
np.random.rand((3))

array([0.13145815, 0.41366737, 0.77872881])

In [14]:
np.random.rand(3,3)

array([[0.58390137, 0.18263144, 0.82608225],
       [0.10540183, 0.28357668, 0.06556327],
       [0.05644419, 0.76545582, 0.01178803]])

In [15]:
np.random.randn(3,3)

array([[-1.58494101,  1.05535316, -1.92657911],
       [ 0.69858388, -0.74620143, -0.15662666],
       [-0.19363594,  1.13912535,  0.36221796]])

In [16]:
x = [1,2,3,4]
np.random.choice(x)

1

In [18]:
for i in range(0,11):
    print(np.random.choice(x))

1
1
2
1
4
1
1
3
1
3
3


In [19]:
x

[1, 2, 3, 4]

In [20]:
np.random.permutation(x)

array([3, 4, 2, 1])

In [21]:
np.random.permutation(x)

array([3, 1, 2, 4])